import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.anomalyList": "Anomaly List",
    "nav.anomalyUpload": "Anomaly Upload",
    "nav.maintenanceWindows": "Maintenance Windows",
    "nav.adminPanel": "Admin Panel",
    "nav.signOut": "Sign Out",
    "nav.settings": "Settings",
    "nav.myAccount": "My Account",

    // Login
    "login.welcome": "Welcome Back",
    "login.subtitle": "Sign in to your account to continue",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.signIn": "Sign In",
    "login.emailPlaceholder": "john.doe@company.com",
    "login.passwordPlaceholder": "Enter your password",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of anomaly management system",
    "dashboard.totalAnomalies": "Total Anomalies",
    "dashboard.openAnomalies": "Open Anomalies",
    "dashboard.highCriticality": "High Criticality",
    "dashboard.maintenanceWindows": "Maintenance Windows",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.viewAll": "View All",
    "dashboard.noActivity": "No recent activity",
    "dashboard.activityDescription":
      "Recent anomaly reports and updates will appear here",
    "dashboard.resolvedThisWeek": "resolved this week",
    "dashboard.avgResolutionTime": "Avg.",
    "dashboard.daysToResolve": "days to resolve",
    "dashboard.requireImmediateAttention": "Require immediate attention",
    "dashboard.scheduledForQ1": "Scheduled for Q1 2024",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.viewAllAnomalies": "View All Anomalies",
    "dashboard.manageTrackStatus": "Manage and track anomaly status",
    "dashboard.uploadClassify": "Upload & Classify",
    "dashboard.useAIPredictCriticality":
      "Use AI to predict anomaly criticality",
    "dashboard.maintenancePlanning": "Maintenance Planning",
    "dashboard.scheduleManageWindows":
      "Schedule and manage maintenance windows",
    "dashboard.minAgo": "min ago",
    "dashboard.hAgo": "h ago",
    "dashboard.aiAgreementRate": "AI Agreement Rate",
    "dashboard.aiHumanAlignment": "AI-Human alignment score",

    // Anomaly List
    "anomalyList.title": "Anomaly List",
    "anomalyList.subtitle":
      "View and manage all reported anomalies with enhanced classification",
    "anomalyList.search": "Search anomalies...",
    "anomalyList.allStatus": "All Status",
    "anomalyList.allCriticality": "All Criticality",
    "anomalyList.equipment": "Equipment",
    "anomalyList.systemId": "System ID",
    "anomalyList.description": "Description",
    "anomalyList.section": "Section",
    "anomalyList.criticality": "Criticality",
    "anomalyList.status": "Status",
    "anomalyList.date": "Date",
    "anomalyList.maintenance": "Maintenance",
    "anomalyList.editClassification": "Edit Classification",
    "anomalyList.viewDetails": "View Details",
    "anomalyList.delete": "Delete",
    "anomalyList.noShutdown": "No shutdown",
    "anomalyList.linked": "Linked",
    "anomalyList.days": "days",
    "anomalyList.filtersSearch": "Filters & Search",
    "anomalyList.showing": "Showing",
    "anomalyList.of": "of",
    "anomalyList.anomalies": "anomalies",
    "anomalyList.selected": "selected",
    "anomalyList.bulkActions": "Bulk Actions",
    "anomalyList.allUnits": "All Units",
    "anomalyList.newestFirst": "Newest First",
    "anomalyList.oldestFirst": "Oldest First",
    "anomalyList.byCriticality": "By Criticality",
    "anomalyList.byEquipment": "By Equipment",
    "anomalyList.noAnomaliesFound": "No anomalies found",
    "anomalyList.adjustCriteria":
      "Try adjusting your search or filter criteria",
    "anomalyList.editClassificationTitle": "Edit Anomaly Classification",
    "anomalyList.editClassificationDesc":
      "Update the criticality scores and maintenance requirements for this anomaly.",
    "anomalyList.validationError": "Validation Error",
    "anomalyList.fillAllFields": "Please fill in all required fields",
    "anomalyList.anomalyUpdated": "Anomaly Updated",
    "anomalyList.updateSuccess": "The anomaly has been updated successfully",
    "anomalyList.maintenanceDurationDays": "Maintenance Duration (days)",
    "anomalyList.suggestedMaintenanceWindow": "Suggested Maintenance Window",
    "anomalyList.selectMaintenanceWindow": "Select maintenance window",
    "anomalyList.maintenanceWindowSuggested": "Maintenance Window Suggested",
    "anomalyList.matchesRequirement": "matches your",
    "anomalyList.dayRequirement": "day requirement",
    "anomalyList.equipmentInfo": "Equipment Info",
    "anomalyList.anomalyInfo": "Anomaly Info",
    "anomalyList.manageRex": "Manage REX",
    "anomalyList.rexTitle": "Retour d'Expérience (REX)",
    "anomalyList.rexDescription":
      "Add notes and attachments for lessons learned from this resolved anomaly.",
    "anomalyList.rexNotes": "REX Notes",
    "anomalyList.rexNotesPlaceholder":
      "Enter lessons learned, root cause analysis, preventive measures, etc...",
    "anomalyList.rexAttachments": "Attachments",
    "anomalyList.attachedFiles": "Attached Files",
    "anomalyList.rexLastUpdated": "Last updated",
    "anomalyList.saveRex": "Save REX",
    "anomalyList.rexSaved": "REX Saved",
    "anomalyList.rexSavedDesc":
      "Retour d'expérience has been saved successfully",
    "anomalyList.manageActionPlan": "Manage Action Plan",
    "anomalyList.actionPlanTitle": "Maintenance Action Plan",
    "anomalyList.actionPlanDescription":
      "Create a detailed action plan for resolving this anomaly during maintenance shutdown.",
    "anomalyList.actionPlanDescLabel": "Action Plan Description",
    "anomalyList.actionPlanDescPlaceholder":
      "Enter detailed description of the action plan...",
    "anomalyList.actionSteps": "Action Steps",
    "anomalyList.step": "Step",
    "anomalyList.addStep": "Add Step",
    "anomalyList.estimatedDuration": "Estimated Duration",
    "anomalyList.responsiblePerson": "Responsible Person",
    "anomalyList.responsiblePersonPlaceholder": "Enter responsible person name",
    "anomalyList.requiredResources": "Required Resources",
    "anomalyList.resource": "Resource",
    "anomalyList.addResource": "Add Resource",
    "anomalyList.actionPlanStatus": "Action Plan Status",
    "anomalyList.statusDraft": "Draft",
    "anomalyList.statusApproved": "Approved",
    "anomalyList.statusInProgress": "In Progress",
    "anomalyList.statusCompleted": "Completed",
    "anomalyList.actionPlanLastUpdated": "Action plan last updated",
    "anomalyList.saveActionPlan": "Save Action Plan",
    "anomalyList.actionPlanSaved": "Action Plan Saved",
    "anomalyList.actionPlanSavedDesc":
      "The action plan has been saved successfully",
    "anomalyList.filtered": "filtered",
    "anomalyList.from": "from",
    "anomalyList.itemsPerPage": "Items per page",
    "anomalyList.page": "Page",
    "anomalyList.first": "First",
    "anomalyList.previous": "Previous",
    "anomalyList.next": "Next",
    "anomalyList.on": "on",
    "anomalyList.total": "Total",
    "anomalyList.pages": "pages",
    "anomalyList.last": "Last",
    "common.by": "by",

    // Anomaly Details
    "anomalyDetails.title": "Anomaly",
    "anomalyDetails.equipmentInfo": "Equipment Information",
    "anomalyDetails.statusPriority": "Status",
    "anomalyDetails.description": "Anomaly Description",
    "anomalyDetails.criticalityAssessment": "Criticality Assessment",
    "anomalyDetails.reportedBy": "Reported By",
    "anomalyDetails.assignedTo": "Assigned To",
    "anomalyDetails.notAssigned": "Not assigned",
    "anomalyDetails.activityTimeline": "Activity Timeline",
    "anomalyDetails.addComment": "Add Comment",
    "anomalyDetails.addCommentPlaceholder": "Add a comment...",
    "anomalyDetails.maintenancePlanning": "Maintenance Planning",
    "anomalyDetails.requiresShutdown": "Requires Maintenance Shutdown",
    "anomalyDetails.duration": "Maintenance Duration (days)",
    "anomalyDetails.linkedWindow": "Linked Maintenance Window",
    "anomalyDetails.selectWindow": "Select maintenance window",
    "anomalyDetails.estimatedCost": "Estimated Cost (MAD)",
    "anomalyDetails.actualCost": "Actual Cost (MAD)",
    "anomalyDetails.preventiveActions": "Preventive Actions",
    "anomalyDetails.equipmentNumber": "Equipment Number",
    "anomalyDetails.systemId": "System ID",
    "anomalyDetails.equipmentDescription": "Equipment Description",
    "anomalyDetails.sectionProprietaire": "Section Propriétaire",
    "anomalyDetails.status": "Status",
    "anomalyDetails.priority": "Priority",
    "anomalyDetails.detectionDate": "Detection Date",
    "anomalyDetails.fiabiliteIntegrite": "Fiabilité Intégrité (1-5)",
    "anomalyDetails.disponibilite": "Disponibilité (1-5)",
    "anomalyDetails.processSafety": "Process Safety (1-5)",
    "anomalyDetails.totalCriticality": "Total Criticality",
    "anomalyDetails.autoCalculated":
      "Automatically calculated as sum of the three criteria above",
    "anomalyDetails.updated": "Anomaly Updated",
    "anomalyDetails.updatedSuccess":
      "The anomaly details have been saved successfully.",
    "anomalyDetails.statusUpdated": "Status Updated",
    "anomalyDetails.commentAdded": "Comment Added",
    "anomalyDetails.commentSuccess":
      "Your comment has been added to the anomaly.",
    "anomalyDetails.notFound": "Anomaly Not Found",
    "anomalyDetails.notFoundDesc": "The requested anomaly could not be found.",
    "anomalyDetails.tabs.details": "Details",
    "anomalyDetails.tabs.timeline": "Timeline",
    "anomalyDetails.tabs.maintenance": "Maintenance",

    // Maintenance Windows
    "maintenanceWindows.title": "Maintenance Windows",
    "maintenanceWindows.subtitle":
      "Manage and schedule maintenance windows for anomaly resolution",
    "maintenanceWindows.createWindow": "Create Window",
    "maintenanceWindows.totalWindows": "Total Windows",
    "maintenanceWindows.planned": "Planned",
    "maintenanceWindows.assignedAnomalies": "Assigned Anomalies",
    "maintenanceWindows.totalCapacity": "Total Capacity",
    "maintenanceWindows.name": "Name",
    "maintenanceWindows.type": "Type",
    "maintenanceWindows.status": "Status",
    "maintenanceWindows.duration": "Duration",
    "maintenanceWindows.dateRange": "Date Range",
    "maintenanceWindows.utilization": "Utilization",
    "maintenanceWindows.days": "days",
    "maintenanceWindows.to": "to",
    "maintenanceWindows.edit": "Edit",
    "maintenanceWindows.delete": "Delete",
    "maintenanceWindows.noWindows": "No maintenance windows",
    "maintenanceWindows.createFirst":
      "Create your first maintenance window to start scheduling anomaly resolutions",
    "maintenanceWindows.createWindowDialog": "Create Maintenance Window",
    "maintenanceWindows.createWindowDesc":
      "Create a new maintenance window for scheduling anomaly resolutions.",
    "maintenanceWindows.editWindowDialog": "Edit Maintenance Window",
    "maintenanceWindows.editWindowDesc":
      "Update the maintenance window details below.",
    "maintenanceWindows.windowName": "Name",
    "maintenanceWindows.description": "Description",
    "maintenanceWindows.startDate": "Start Date",
    "maintenanceWindows.endDate": "End Date",
    "maintenanceWindows.capacity": "Capacity",
    "maintenanceWindows.maxAnomalies": "Max anomalies",
    "maintenanceWindows.createWindow": "Create Window",
    "maintenanceWindows.updateWindow": "Update Window",
    "maintenanceWindows.validationError": "Validation Error",
    "maintenanceWindows.fillAllFields": "Please fill in all required fields",
    "maintenanceWindows.endAfterStart": "End date must be after start date",
    "maintenanceWindows.windowCreated": "Maintenance Window Created",
    "maintenanceWindows.windowUpdated": "Maintenance Window Updated",
    "maintenanceWindows.createSuccess": "has been created successfully",
    "maintenanceWindows.updateSuccess": "has been updated successfully",
    "maintenanceWindows.cannotDelete": "Cannot Delete",
    "maintenanceWindows.cannotDeleteDesc":
      "Cannot delete maintenance window with assigned anomalies",
    "maintenanceWindows.windowDeleted": "Maintenance Window Deleted",
    "maintenanceWindows.deleteSuccess":
      "The maintenance window has been deleted successfully",
    "maintenanceWindows.statusPlanned": "Planned",
    "maintenanceWindows.statusActive": "Active",
    "maintenanceWindows.statusCompleted": "Completed",
    "maintenanceWindows.statusCancelled": "Cancelled",
    "maintenanceWindows.statusUpdated": "Status Updated",
    "maintenanceWindows.statusUpdateSuccess":
      "Maintenance window status has been updated",

    // Anomaly Upload
    "anomalyUpload.title": "Anomaly Processing & AI Classification",
    "anomalyUpload.subtitle":
      "Upload anomaly files and get AI-powered criticality predictions with maintenance planning using QWEN model",
    "anomalyUpload.fileUpload": "File Upload & Processing",
    "anomalyUpload.results": "Classification Results",
    "anomalyUpload.kpis": "Model Performance",
    "anomalyUpload.uploadExcel": "Upload Excel File",
    "anomalyUpload.selectFile":
      "Select an Excel file containing anomaly data for AI classification",
    "anomalyUpload.fileReady": "File Ready",
    "anomalyUpload.runClassification": "Run AI Classification",
    "anomalyUpload.processing": "Processing...",
    "anomalyUpload.accuracy": "Accuracy",
    "anomalyUpload.f1Score": "F1 Score",
    "anomalyUpload.criticalIssuesFlagged": "Critical Issues Flagged",
    "anomalyUpload.userAgreement": "User Agreement",
    "anomalyUpload.classificationResults": "AI Classification Results",
    "anomalyUpload.predictedCriticality": "Predicted Criticality",
    "anomalyUpload.confidence": "Confidence",
    "anomalyUpload.maintenance": "Maintenance",
    "anomalyUpload.suggestedWindow": "Suggested Window",
    "anomalyUpload.feedback": "Feedback",
    "anomalyUpload.shutdownRequired": "Shutdown required",
    "anomalyUpload.noShutdown": "No shutdown",
    "anomalyUpload.selectWindow": "Select window",
    "anomalyUpload.noResultsYet": "No Results Yet",
    "anomalyUpload.noResultsDesc":
      "Upload and process an anomaly file to see AI classification results",
    "anomalyUpload.modelPerformance": "Model Performance Metrics",
    "anomalyUpload.classificationStats": "Classification Statistics",
    "anomalyUpload.totalPredictions": "Total Predictions",
    "anomalyUpload.correctPredictions": "Correct Predictions",
    "anomalyUpload.userCorrections": "User Corrections",
    "anomalyUpload.maintenanceWindow": "Maintenance Window",
    "anomalyUpload.addWindow": "Add Window",
    "anomalyUpload.removeWindow": "Remove Window",
    "anomalyUpload.editMaintenance": "Edit Maintenance Details",
    "anomalyUpload.editMaintenanceDesc":
      "Configure maintenance requirements and window assignment for this anomaly.",
    "anomalyUpload.requiresMaintenance": "Requires Maintenance Shutdown",
    "anomalyUpload.maintenanceDurationDays": "Maintenance Duration (days)",
    "anomalyUpload.selectMaintenanceWindow": "Select Maintenance Window",
    "anomalyUpload.noWindowAvailable": "No suitable window available",
    "anomalyUpload.createNewWindow": "Create New Window",
    "anomalyUpload.windowName": "Window Name",
    "anomalyUpload.startDate": "Start Date",
    "anomalyUpload.endDate": "End Date",
    "anomalyUpload.capacity": "Capacity",
    "anomalyUpload.description": "Description",
    "anomalyUpload.windowType": "Window Type",
    "anomalyUpload.routine": "Routine",
    "anomalyUpload.emergency": "Emergency",
    "anomalyUpload.shutdown": "Shutdown",
    "anomalyUpload.saveChanges": "Save Changes",
    "anomalyUpload.cancel": "Cancel",

    // Common
    "common.actions": "Actions",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.create": "Create",
    "common.update": "Update",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.high": "High",
    "common.medium": "Medium",
    "common.low": "Low",
    "common.open": "Open",
    "common.inProgress": "In Progress",
    "common.resolved": "Resolved",
    "common.archived": "Archived",
    "common.back": "Back",
    "common.add": "Add",
    "common.saveChanges": "Save Changes",
    "common.critical": "Critical",
    "common.priority": "Priority",
    "common.status": "Status",
  },
  fr: {
    // Navigation
    "nav.dashboard": "Tableau de Bord",
    "nav.anomalyList": "Liste des Anomalies",
    "nav.anomalyUpload": "Upload Anomalies",
    "nav.maintenanceWindows": "Fenêtres de Maintenance",
    "nav.adminPanel": "Panneau Admin",
    "nav.signOut": "Se Déconnecter",
    "nav.settings": "Paramètres",
    "nav.myAccount": "Mon Compte",

    // Login
    "login.welcome": "Bon Retour",
    "login.subtitle": "Connectez-vous à votre compte pour continuer",
    "login.email": "Adresse Email",
    "login.password": "Mot de Passe",
    "login.signIn": "Se Connecter",
    "login.emailPlaceholder": "jean.dupont@entreprise.com",
    "login.passwordPlaceholder": "Entrez votre mot de passe",

    // Dashboard
    "dashboard.title": "Tableau de Bord",
    "dashboard.subtitle": "Aperçu du système de gestion des anomalies",
    "dashboard.totalAnomalies": "Total Anomalies",
    "dashboard.openAnomalies": "Anomalies Ouvertes",
    "dashboard.highCriticality": "Criticité Élevée",
    "dashboard.maintenanceWindows": "Fenêtres de Maintenance",
    "dashboard.recentActivity": "Activité Récente",
    "dashboard.viewAll": "Voir Tout",
    "dashboard.noActivity": "Aucune activité récente",
    "dashboard.activityDescription":
      "Les rapports et mises à jour récents d'anomalies apparaîtront ici",
    "dashboard.resolvedThisWeek": "résolues cette semaine",
    "dashboard.avgResolutionTime": "Moy.",
    "dashboard.daysToResolve": "jours pour résoudre",
    "dashboard.requireImmediateAttention": "Nécessitent attention immédiate",
    "dashboard.scheduledForQ1": "Planifiées pour T1 2024",
    "dashboard.quickActions": "Actions Rapides",
    "dashboard.viewAllAnomalies": "Voir Toutes Anomalies",
    "dashboard.manageTrackStatus": "Gérer et suivre statut anomalies",
    "dashboard.uploadClassify": "Télécharger & Classifier",
    "dashboard.useAIPredictCriticality":
      "Utiliser IA pour prédire criticité anomalie",
    "dashboard.maintenancePlanning": "Planification Maintenance",
    "dashboard.scheduleManageWindows":
      "Planifier et gérer fenêtres de maintenance",
    "dashboard.minAgo": "min passées",
    "dashboard.hAgo": "h passées",
    "dashboard.aiAgreementRate": "Taux Accord IA",
    "dashboard.aiHumanAlignment": "Score alignement IA-Humain",

    // Anomaly List
    "anomalyList.title": "Liste des Anomalies",
    "anomalyList.subtitle":
      "Voir et gérer toutes les anomalies signalées avec classification améliorée",
    "anomalyList.search": "Rechercher anomalies...",
    "anomalyList.allStatus": "Tous les Statuts",
    "anomalyList.allCriticality": "Toutes Criticités",
    "anomalyList.equipment": "Équipement",
    "anomalyList.systemId": "ID Système",
    "anomalyList.description": "Description",
    "anomalyList.section": "Section",
    "anomalyList.criticality": "Criticité",
    "anomalyList.status": "Statut",
    "anomalyList.date": "Date",
    "anomalyList.maintenance": "Maintenance",
    "anomalyList.editClassification": "Modifier Classification",
    "anomalyList.viewDetails": "Voir Détails",
    "anomalyList.delete": "Supprimer",
    "anomalyList.noShutdown": "Pas d'arrêt",
    "anomalyList.linked": "Lié",
    "anomalyList.days": "jours",
    "anomalyList.filtersSearch": "Filtres & Recherche",
    "anomalyList.showing": "Affichage",
    "anomalyList.of": "de",
    "anomalyList.anomalies": "anomalies",
    "anomalyList.selected": "sélectionnées",
    "anomalyList.bulkActions": "Actions Groupées",
    "anomalyList.allUnits": "Toutes Unités",
    "anomalyList.newestFirst": "Plus Récent D'abord",
    "anomalyList.oldestFirst": "Plus Ancien D'abord",
    "anomalyList.byCriticality": "Par Criticité",
    "anomalyList.byEquipment": "Par Équipement",
    "anomalyList.noAnomaliesFound": "Aucune anomalie trouvée",
    "anomalyList.adjustCriteria":
      "Essayez d'ajuster vos critères de recherche ou de filtre",
    "anomalyList.editClassificationTitle": "Modifier Classification Anomalie",
    "anomalyList.editClassificationDesc":
      "Mettre à jour les scores de criticité et les exigences de maintenance pour cette anomalie.",
    "anomalyList.validationError": "Erreur de Validation",
    "anomalyList.fillAllFields": "Veuillez remplir tous les champs requis",
    "anomalyList.anomalyUpdated": "Anomalie Mise à Jour",
    "anomalyList.updateSuccess": "L'anomalie a été mise à jour avec succès",
    "anomalyList.maintenanceDurationDays": "Durée Maintenance (jours)",
    "anomalyList.suggestedMaintenanceWindow": "Fenêtre Maintenance Suggérée",
    "anomalyList.selectMaintenanceWindow":
      "Sélectionner fenêtre de maintenance",
    "anomalyList.maintenanceWindowSuggested": "Fenêtre de Maintenance Suggérée",
    "anomalyList.matchesRequirement": "correspond à votre exigence de",
    "anomalyList.dayRequirement": "jours",
    "anomalyList.equipmentInfo": "Info Équipement",
    "anomalyList.anomalyInfo": "Info Anomalie",
    "anomalyList.manageRex": "Gérer REX",
    "anomalyList.rexTitle": "Retour d'Expérience (REX)",
    "anomalyList.rexDescription":
      "Ajouter des notes et pièces jointes pour les leçons apprises de cette anomalie résolue.",
    "anomalyList.rexNotes": "Notes REX",
    "anomalyList.rexNotesPlaceholder":
      "Entrez les leçons apprises, analyse des causes, mesures préventives, etc...",
    "anomalyList.rexAttachments": "Pièces Jointes",
    "anomalyList.attachedFiles": "Fichiers Joints",
    "anomalyList.rexLastUpdated": "Dernière mise à jour",
    "anomalyList.saveRex": "Enregistrer REX",
    "anomalyList.rexSaved": "REX Enregistré",
    "anomalyList.rexSavedDesc":
      "Le retour d'expérience a été enregistré avec succès",
    "anomalyList.manageActionPlan": "Gérer Plan d'Action",
    "anomalyList.actionPlanTitle": "Plan d'Action Maintenance",
    "anomalyList.actionPlanDescription":
      "Créer un plan d'action détaillé pour résoudre cette anomalie pendant l'arrêt de maintenance.",
    "anomalyList.actionPlanDescLabel": "Description Plan d'Action",
    "anomalyList.actionPlanDescPlaceholder":
      "Entrez une description détaillée du plan d'action...",
    "anomalyList.actionSteps": "Étapes d'Action",
    "anomalyList.step": "Étape",
    "anomalyList.addStep": "Ajouter Étape",
    "anomalyList.estimatedDuration": "Durée Estimée",
    "anomalyList.responsiblePerson": "Personne Responsable",
    "anomalyList.responsiblePersonPlaceholder":
      "Entrez le nom de la personne responsable",
    "anomalyList.requiredResources": "Ressources Requises",
    "anomalyList.resource": "Ressource",
    "anomalyList.addResource": "Ajouter Ressource",
    "anomalyList.actionPlanStatus": "Statut Plan d'Action",
    "anomalyList.statusDraft": "Brouillon",
    "anomalyList.statusApproved": "Approuvé",
    "anomalyList.statusInProgress": "En Cours",
    "anomalyList.statusCompleted": "Terminé",
    "anomalyList.actionPlanLastUpdated": "Plan d'action dernière mise à jour",
    "anomalyList.saveActionPlan": "Enregistrer Plan d'Action",
    "anomalyList.actionPlanSaved": "Plan d'Action Enregistré",
    "anomalyList.actionPlanSavedDesc":
      "Le plan d'action a été enregistré avec succès",
    "anomalyList.filtered": "filtrées",
    "anomalyList.from": "sur",
    "anomalyList.itemsPerPage": "Éléments par page",
    "anomalyList.page": "Page",
    "anomalyList.first": "Premier",
    "anomalyList.previous": "Précédent",
    "anomalyList.next": "Suivant",
    "anomalyList.on": "sur",
    "anomalyList.total": "Total",
    "anomalyList.pages": "pages",
    "anomalyList.last": "Dernier",
    "common.by": "par",

    // Anomaly Details
    "anomalyDetails.title": "Anomalie",
    "anomalyDetails.equipmentInfo": "Informations Équipement",
    "anomalyDetails.statusPriority": "Statut",
    "anomalyDetails.description": "Description de l'Anomalie",
    "anomalyDetails.criticalityAssessment": "Évaluation de la Criticité",
    "anomalyDetails.reportedBy": "Signalé par",
    "anomalyDetails.assignedTo": "Assigné à",
    "anomalyDetails.notAssigned": "Non assigné",
    "anomalyDetails.activityTimeline": "Chronologie des Activités",
    "anomalyDetails.addComment": "Ajouter Commentaire",
    "anomalyDetails.addCommentPlaceholder": "Ajouter un commentaire...",
    "anomalyDetails.maintenancePlanning": "Planification Maintenance",
    "anomalyDetails.requiresShutdown": "Nécessite Arrêt de Maintenance",
    "anomalyDetails.duration": "Durée Maintenance (jours)",
    "anomalyDetails.linkedWindow": "Fenêtre de Maintenance Liée",
    "anomalyDetails.selectWindow": "Sélectionner fenêtre de maintenance",
    "anomalyDetails.estimatedCost": "Coût Estimé (MAD)",
    "anomalyDetails.actualCost": "Coût Réel (MAD)",
    "anomalyDetails.preventiveActions": "Actions Préventives",
    "anomalyDetails.equipmentNumber": "Numéro Équipement",
    "anomalyDetails.systemId": "ID Système",
    "anomalyDetails.equipmentDescription": "Description Équipement",
    "anomalyDetails.sectionProprietaire": "Section Propriétaire",
    "anomalyDetails.status": "Statut",
    "anomalyDetails.priority": "Priorité",
    "anomalyDetails.detectionDate": "Date de Détection",
    "anomalyDetails.fiabiliteIntegrite": "Fiabilité Intégrité (1-5)",
    "anomalyDetails.disponibilite": "Disponibilité (1-5)",
    "anomalyDetails.processSafety": "Sécurité Processus (1-5)",
    "anomalyDetails.totalCriticality": "Criticité Totale",
    "anomalyDetails.autoCalculated":
      "Calculé automatiquement comme somme des trois critères ci-dessus",
    "anomalyDetails.updated": "Anomalie Mise à Jour",
    "anomalyDetails.updatedSuccess":
      "Les détails de l'anomalie ont été sauvegardés avec succès.",
    "anomalyDetails.statusUpdated": "Statut Mis à Jour",
    "anomalyDetails.commentAdded": "Commentaire Ajouté",
    "anomalyDetails.commentSuccess":
      "Votre commentaire a été ajouté à l'anomalie.",
    "anomalyDetails.notFound": "Anomalie Non Trouvée",
    "anomalyDetails.notFoundDesc":
      "L'anomalie demandée n'a pas pu être trouvée.",
    "anomalyDetails.tabs.details": "Détails",
    "anomalyDetails.tabs.timeline": "Chronologie",
    "anomalyDetails.tabs.maintenance": "Maintenance",

    // Maintenance Windows
    "maintenanceWindows.title": "Fenêtres de Maintenance",
    "maintenanceWindows.subtitle":
      "Gérer et planifier les fenêtres de maintenance pour la résolution d'anomalies",
    "maintenanceWindows.createWindow": "Créer Fenêtre",
    "maintenanceWindows.totalWindows": "Total Fenêtres",
    "maintenanceWindows.planned": "Planifiées",
    "maintenanceWindows.assignedAnomalies": "Anomalies Assignées",
    "maintenanceWindows.totalCapacity": "Capacité Totale",
    "maintenanceWindows.name": "Nom",
    "maintenanceWindows.type": "Type",
    "maintenanceWindows.status": "Statut",
    "maintenanceWindows.duration": "Durée",
    "maintenanceWindows.dateRange": "Plage de Dates",
    "maintenanceWindows.utilization": "Utilisation",
    "maintenanceWindows.days": "jours",
    "maintenanceWindows.to": "à",
    "maintenanceWindows.edit": "Modifier",
    "maintenanceWindows.delete": "Supprimer",
    "maintenanceWindows.noWindows": "Aucune fenêtre de maintenance",
    "maintenanceWindows.createFirst":
      "Créez votre première fenêtre de maintenance pour commencer à planifier les résolutions d'anomalies",
    "maintenanceWindows.createWindowDialog": "Créer Fenêtre de Maintenance",
    "maintenanceWindows.createWindowDesc":
      "Créer une nouvelle fenêtre de maintenance pour planifier les résolutions d'anomalies.",
    "maintenanceWindows.editWindowDialog": "Modifier Fenêtre de Maintenance",
    "maintenanceWindows.editWindowDesc":
      "Mettre à jour les détails de la fenêtre de maintenance ci-dessous.",
    "maintenanceWindows.windowName": "Nom",
    "maintenanceWindows.description": "Description",
    "maintenanceWindows.startDate": "Date Début",
    "maintenanceWindows.endDate": "Date Fin",
    "maintenanceWindows.capacity": "Capacité",
    "maintenanceWindows.maxAnomalies": "Max anomalies",
    "maintenanceWindows.createWindow": "Créer Fenêtre",
    "maintenanceWindows.updateWindow": "Mettre à Jour Fenêtre",
    "maintenanceWindows.validationError": "Erreur de Validation",
    "maintenanceWindows.fillAllFields":
      "Veuillez remplir tous les champs requis",
    "maintenanceWindows.endAfterStart":
      "La date de fin doit être après la date de début",
    "maintenanceWindows.windowCreated": "Fenêtre de Maintenance Créée",
    "maintenanceWindows.windowUpdated": "Fenêtre de Maintenance Mise à Jour",
    "maintenanceWindows.createSuccess": "a été créée avec succès",
    "maintenanceWindows.updateSuccess": "a été mise à jour avec succès",
    "maintenanceWindows.cannotDelete": "Impossible de Supprimer",
    "maintenanceWindows.cannotDeleteDesc":
      "Impossible de supprimer une fenêtre de maintenance avec des anomalies assignées",
    "maintenanceWindows.windowDeleted": "Fenêtre de Maintenance Supprimée",
    "maintenanceWindows.deleteSuccess":
      "La fenêtre de maintenance a été supprimée avec succès",
    "maintenanceWindows.statusPlanned": "Planifiée",
    "maintenanceWindows.statusActive": "Active",
    "maintenanceWindows.statusCompleted": "Terminée",
    "maintenanceWindows.statusCancelled": "Annulée",
    "maintenanceWindows.statusUpdated": "Statut Mis à Jour",
    "maintenanceWindows.statusUpdateSuccess":
      "Le statut de la fenêtre de maintenance a été mis à jour",

    // Anomaly Upload
    "anomalyUpload.title": "Traitement Anomalies & Classification IA",
    "anomalyUpload.subtitle":
      "Téléchargez des fichiers d'anomalies et obtenez des prédictions de criticité alimentées par l'IA avec planification de maintenance utilisant le modèle QWEN",
    "anomalyUpload.fileUpload": "Téléchargement & Traitement Fichier",
    "anomalyUpload.results": "Résultats Classification",
    "anomalyUpload.kpis": "Performance du Modèle",
    "anomalyUpload.uploadExcel": "Télécharger Fichier Excel",
    "anomalyUpload.selectFile":
      "Sélectionnez un fichier Excel contenant les données d'anomalies pour classification IA",
    "anomalyUpload.fileReady": "Fichier Prêt",
    "anomalyUpload.runClassification": "Lancer Classification IA",
    "anomalyUpload.processing": "Traitement...",
    "anomalyUpload.accuracy": "Précision",
    "anomalyUpload.f1Score": "Score F1",
    "anomalyUpload.criticalIssuesFlagged": "Problèmes Critiques Signalés",
    "anomalyUpload.userAgreement": "Accord Utilisateur",
    "anomalyUpload.classificationResults": "Résultats Classification IA",
    "anomalyUpload.predictedCriticality": "Criticité Prédite",
    "anomalyUpload.confidence": "Confiance",
    "anomalyUpload.maintenance": "Maintenance",
    "anomalyUpload.suggestedWindow": "Fenêtre Suggérée",
    "anomalyUpload.feedback": "Retour",
    "anomalyUpload.shutdownRequired": "Arrêt requis",
    "anomalyUpload.noShutdown": "Pas d'arrêt",
    "anomalyUpload.selectWindow": "Sélectionner fenêtre",
    "anomalyUpload.noResultsYet": "Aucun Résultat Encore",
    "anomalyUpload.noResultsDesc":
      "Téléchargez et traitez un fichier d'anomalies pour voir les résultats de classification IA",
    "anomalyUpload.modelPerformance": "Métriques Performance Modèle",
    "anomalyUpload.classificationStats": "Statistiques Classification",
    "anomalyUpload.totalPredictions": "Total Prédictions",
    "anomalyUpload.correctPredictions": "Prédictions Correctes",
    "anomalyUpload.userCorrections": "Corrections Utilisateur",
    "anomalyUpload.maintenanceWindow": "Fenêtre Maintenance",
    "anomalyUpload.addWindow": "Ajouter Fenêtre",
    "anomalyUpload.removeWindow": "Supprimer Fenêtre",
    "anomalyUpload.editMaintenance": "Modifier Détails Maintenance",
    "anomalyUpload.editMaintenanceDesc":
      "Configurer les exigences de maintenance et l'attribution de fenêtre pour cette anomalie.",
    "anomalyUpload.requiresMaintenance": "Nécessite Arrêt Maintenance",
    "anomalyUpload.maintenanceDurationDays": "Durée Maintenance (jours)",
    "anomalyUpload.selectMaintenanceWindow": "Sélectionner Fenêtre Maintenance",
    "anomalyUpload.noWindowAvailable": "Aucune fenêtre appropriée disponible",
    "anomalyUpload.createNewWindow": "Créer Nouvelle Fenêtre",
    "anomalyUpload.windowName": "Nom Fenêtre",
    "anomalyUpload.startDate": "Date Début",
    "anomalyUpload.endDate": "Date Fin",
    "anomalyUpload.capacity": "Capacité",
    "anomalyUpload.description": "Description",
    "anomalyUpload.windowType": "Type Fenêtre",
    "anomalyUpload.routine": "Routine",
    "anomalyUpload.emergency": "Urgence",
    "anomalyUpload.shutdown": "Arrêt",
    "anomalyUpload.saveChanges": "Enregistrer Modifications",
    "anomalyUpload.cancel": "Annuler",

    // Common
    "common.actions": "Actions",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.create": "Créer",
    "common.update": "Mettre à jour",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.warning": "Avertissement",
    "common.info": "Info",
    "common.high": "Élevé",
    "common.medium": "Moyen",
    "common.low": "Faible",
    "common.open": "Ouvert",
    "common.inProgress": "En Cours",
    "common.resolved": "Résolu",
    "common.archived": "Archivé",
    "common.back": "Retour",
    "common.add": "Ajouter",
    "common.saveChanges": "Enregistrer Modifications",
    "common.critical": "Critique",
    "common.priority": "Priorité",
    "common.status": "Statut",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem(
      "taqamorocco_language",
    ) as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "fr")) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("taqamorocco_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: handleSetLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
